namespace:
  name: flightspecials
app:
  name: flightspecials
deployment:
  name: flightspecials
  replicas: 2
image:
  repository: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/${ECR_REPO}
  tag: ${IMAGE_TAG}
container:
  port: 8080
service:
  name: flightspecials-service
  type: NodePort
  port: 80
ingress:
  name: flightspecials-ingress
