namespace:
  name: flightspecials
app:
  name: flightspecials
  build_number: 0
deployment:
  name: flightspecials
  replicas: 2
image:
  repository: ${ECR_REPO_URI}
  tag: !${IMAGE_TAG}
container:
  port: 8080
service:
  name: flightspecials-service
  type: NodePort
  port: 80
ingress:
  name: flightspecials-ingress
configmap:
  name: flightspecials-configmap
  environment: test
  database_endpoint: ${DATABASE_ENDPOINT}
  database_port: ${DATABASE_PORT}
  database_username: ${DATABASE_USERNAME}
