namespace:
  name: flightspecials
app:
  name: flightspecials
deployment:
  name: flightspecials
  replicas: 2
image:
  repository: ${ECR_REPO_URI}
  tag: ${IMAGE_TAG}
container:
  port: 8080
service:
  name: flightspecials-service
  type: NodePort
  port: 80
ingress:
  name: flightspecials-ingress
